language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install homeassistant
# command to run tests
script:
  - mv secrets.example.yaml secrets.yaml
  - sed -i '/stream:/d' ./configuration.yaml
  - mv google_service_account.example.json google_service_account.json
  - hass --script check_config -c .
