- action:
  - alias: Bright in Lounge
    data:
      transition: 900 # 15 minutes
      brightness_pct: 100
      kelvin: 2700 
      entity_id: group.lounge_lights
    service: light.turn_on
  alias: Lights on at sunset
  condition: []
  id: '1506795142546'
  trigger:
  - event: sunset
    platform: sun
    offset: "-00:25:00"

- alias: Lights Sync (On)
  action:
  - alias: turn switch on
    data:
      entity_id: switch.my_smart_plug
    service: switch.turn_on
  condition: []
  id: '1508056350422'
  trigger:
  - entity_id: light.twigs
    from: 'off'
    platform: state
    to: 'on'

- alias: Lights Sync (Off)
  action:
  - alias: turn switch off
    data:
      entity_id: switch.my_smart_plug
    service: switch.turn_off
  condition: []
  trigger:
  - entity_id: light.twigs
    from: 'on'
    platform: state
    to: 'off'


- alias: BBC One
  trigger:
  - platform: state
    entity_id: input_select.channel
    to: BBC One
  action:
    service: shell_command.bbcone

- alias: BBC Two
  trigger:
  - platform: state
    entity_id: input_select.channel
    to: BBC Two
  action:
    service: shell_command.bbctwo

- alias: ITV
  trigger:
  - platform: state
    entity_id: input_select.channel
    to: ITV
  action:
    service: shell_command.itv

- alias: Channel 4
  trigger:
  - platform: state
    entity_id: input_select.channel
    to: Channel 4
  action:
    service: shell_command.channel4

- alias: Sky 1
  trigger:
  - platform: state
    entity_id: input_select.channel
    to: Sky 1
  action:
    service: shell_command.sky1

- alias: Lights off at night
  action:
  - data:
      entity_id: group.all_lights
    service: light.turn_off
  - data:
      entity_id: switch.my_smart_plug
    service: switch.turn_off
  condition: []
  id: '1509874606449'
  trigger:
    platform: time
    at: '00:30:00'
 
- alias: TV audio input when not playing
  trigger:
    - platform: state
      entity_id: media_player.lounge
      from: 'playing'
    - platform: state
      entity_id: media_player.downstairs
      from: 'playing'
    - platform: state
      entity_id: media_player.entire_house
      from: 'playing'
  condition: []
  action:
    - service: script.optical1

- alias: Chromecast input when playing
  trigger:
    - platform: state
      entity_id: media_player.lounge
      to: 'playing'
    - platform: state
      entity_id: media_player.downstairs
      to: 'playing'
    - platform: state
      entity_id: media_player.entire_house
      to: 'playing'
  condition: []
  action:
    - service: script.optical2

- alias: Dark theme at night
  action:
  - data:
      name: darkorange
    service: frontend.set_theme
  condition: []
  trigger:
    platform: time 
    at: '23:00:00'

- alias: Light theme in day
  action:
  - data:
      name: default
    service: frontend.set_theme
  condition: []
  trigger:
    platform: time
    at: '07:30:00'
