# - platform: ffmpeg
#   name: DaFang3
#   input: -rtsp_transport tcp -i rtsp://192.168.1.61:8554/unicast

- platform: generic
  still_image_url: https://192.168.1.20/snap.jpeg
  stream_source: rtsp://192.168.1.60:7447/5dc03ee469841dcafac57050_0
  name: G3 Flex
