- platform: ffmpeg
  name: DaFang3
  input: -rtsp_transport tcp -i rtsp://192.168.1.61:8554/unicast

- platform: mjpeg
  name: DaFang
  mjpeg_url: http://192.168.1.92/mjpeg
  still_image_url: https://192.168.1.61/cgi-bin/currentpic.cgi