homeassistant: !include home_assistant.yaml

http: !include http.yaml

lovelace:
 mode: yaml

system_health:

system_log:

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend: !include frontend.yaml

input_select: !include_dir_named inputs
# input_slider: !include inputs/input_slider.yaml

input_number:
  servo_control:
    name: Servo Control
    initial: 0
    min: -100
    max: 100
    step: 1
    mode: slider

input_boolean:
  guest_mode:
    name: Guest mode
    initial: off
    icon: mdi:home-account

google:
  client_id: !secret google_calendar_client_id
  client_secret: !secret google_calendar_client_secret

# image_processing:
#  - platform: openalpr_cloud
#    api_key: !secret openalr_api_key
#    region: eu
#    source:
#     - entity_id: camera.mjpeg_camera

# Checks for available updates
updater:
  reporting: false

# Discover some devices automatically
discovery:

ssdp:

zeroconf:

# Allows you to issue voice commands from the frontend in enabled browsers
# conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

map:

# Track the sun
sun:

dialogflow:

intent_script: !include intents.yaml

binary_sensor: !include_dir_merge_list binary_sensors/

sensor: !include_dir_merge_list sensors/

camera: !include cameras.yaml

image_processing:
  - platform: doods
    url: "http://192.168.1.60:8080"
    scan_interval: 10000
    detector: default
    file_out:
      - "/config/www/{{ camera_entity.split('.')[1] }}_latest.jpg"
      - "/config/www/{{ camera_entity.split('.')[1] }}_{{ now().strftime('%Y%m%d_%H%M%S') }}.jpg"
    confidence: 50
    area:
      # Exclude top 6% of image
      top: 0.06
    labels:
      - car
      - cat
      - dog
      - truck
      - person
    source:
      - entity_id: camera.g3_flex
  - platform: tensorflow
    scan_interval: 604800
    source:
      - entity_id: camera.g3_flex
    file_out:
      - "/config/www/{{ camera_entity.split('.')[1] }}_tf_latest.jpg"
      - "/config/www/{{ camera_entity.split('.')[1] }}_tf_{{ now().strftime('%Y%m%d_%H%M%S') }}.jpg"
    model:
      graph: /config/tensorflow/frozen_inference_graph.pb

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say
  - platform: microsoft
    api_key: !secret microsoft_api_key
    language: en-gb
    gender: Female
    type: Susan, Apollo
    rate: 20

config:

mqtt:
  discovery: true
  discovery_prefix: homeassistant
  broker: !secret mqtt_address
  username: !secret mqtt_username
  password: !secret mqtt_password
  client_id: home-assistant
  port: 443
  certificate: /etc/ssl/certs/ca-certificates.crt

light: !include lights.yaml

hue:
  bridges:
    - host: 192.168.1.16
      allow_hue_groups: false
      allow_unreachable: true

media_player:
  - platform: samsungtv
    host: 192.168.1.115
    mac: !secret samsung_tv_mac
  - platform: spotify
    client_id: !secret spotify_client_id
    client_secret: !secret spotify_client_secret
  - platform: plex
  - platform: androidtv
    name: Bedroom Android TV
    host: 192.168.1.234

device_tracker:
  - platform: asuswrt
    host: 192.168.1.1
    username: !secret router_username
    password: !secret router_password
    interval_seconds: 10
    consider_home: 180
    track_new_devices: yes

asuswrt:
  host: 192.168.1.1
  username: !secret router_username
  password: !secret router_password

switch: !include switches.yaml

automation: !include_dir_merge_list automations/

alert: !include alerts.yaml

notify: !include notifiers.yaml

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

netatmo:
  api_key: !secret netatmo_client_id
  secret_key: !secret netatmo_client_secret
  username: !secret netatmo_username
  password: !secret netatmo_password

ifttt:
  key: !secret ifttt_key

script: !include_dir_named scripts

digital_ocean:
  access_token: !secret digital_ocean_key

logger:
  default: warning

group: !include groups.yaml

scene: !include scenes.yaml

google_assistant:
  project_id: edson-home
  api_key: !secret google_assistant_api_key
  exposed_domains:
    - switch
    - light
    - climate
    - camera
  entity_config:
    light.cupboard:
      name: Cupboard lights
      aliases:
        - Kitchen Counter Lights
        - Coloured Lights
      expose: true

#calendar:
#  - platform: todoist
#    token: !secret todoist_api_token
#    custom_projects:
#      - name: 'Due Today'
#        due_date_days: 0
#      - name: 'Due This Week'
#        due_date_days: 7

shell_command:
  generate_gif: 'convert -delay 100 -loop 0 /config/www/g3_flex_2*.jpg /config/www/g3_flex.gif'

weather:
 - platform: darksky
   api_key: !secret darksky_api_key

history_graph:
  travel_time:
    name: Travel Time
    hours_to_show: 72
    refresh: 60
    entities:
      - sensor.time_to_home
      - sensor.time_to_work

  games:
    name: Games Played
    hours_to_show: 168
    refresh: 30
    entities:
      - sensor.steam_76561198059721761
      - media_player.playstation_4

  temperatures:
     name: Temperature
     hours_to_show: 168
     refresh: 15
     entities:
       - sensor.house_temperature
       - sensor.landing_sensor_temperature
       - sensor.outside_temperature

media_extractor:

zone:
  - name: Work
    latitude: !secret work_lat
    longitude: !secret work_long
    radius: 150
    icon: mdi:brush

xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - key: !secret xiaomi_gateway
      mac: '78:11:DC:B2:5E:74'

alarm_control_panel:
  - platform: manual
    name: House Alarm
    code: !secret alarm_code
    delay_time: 30
    armed_home:
      pending_time: 0
      delay_time: 0

duckdns:
  domain: !secret duck_dns_domain
  access_token: !secret duck_dns_token

recorder:
  purge_keep_days: 21
  db_url: !secret db_url

person: !include people.yaml

tplink:

stream:

#prometheus:
#  namespace: ha

speedtestdotnet:
  monitored_conditions:
    - ping
    - download
    - upload
  scan_interval:
    hours: 3

rest_command:
  find_phone:
    url: 'http://192.168.1.60:5000/command?message=Find my phone'

plant:
  sunflower:
    sensors:
      moisture: sensor.xiaomi_miflora_moisture
      battery: sensor.xiaomi_miflora_battery_level
      temperature: sensor.xiaomi_miflora_temperature
      conductivity: sensor.xiaomi_miflora_soil_conductivity
      brightness: sensor.xiaomi_miflora_illuminance
    min_moisture: 20
    max_moisture: 65
    min_temperature: 8
    max_temperature: 35

climate:
  - platform: netatmo
  - platform: generic_thermostat
    name: Home Office
    heater: switch.office_heating
    target_sensor: sensor.temperature_158d00027265db
    ac_mode: false
    max_temp: 20
    min_temp: 17.5
    away_temp: 10
    min_cycle_duration:
      seconds: 30
    keep_alive:
      minutes: 3
    initial_hvac_mode: "heat"

timer:
  bedroom_sleep_timer:
    duration: '00:30:00'

telegram_bot:
  - platform: webhooks
    api_key: !secret telegram_secret
    parse_mode: html
    allowed_chat_ids: !secret telegram_chats

panel_iframe: !secret panels

vacuum:
  - platform: xiaomi_miio
    host: 192.168.1.216
    token: !secret roborock_token

owntracks:
  max_gps_accuracy: 200

tuya:
  username: !secret phone_number
  password: !secret tuya_pass
  country_code: "44"
  platform: smart_life

octoprint:
  host: octopi
  api_key: !secret octoprint_api
