hassio:

homeassistant: !include home_assistant.yaml

http: !include http.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend: !include frontend.yaml

input_select: !include inputs/input_select.yaml
# input_slider: !include inputs/input_slider.yaml

shell_command: !include shell_commands.yaml


# image_processing:
#  - platform: openalpr_cloud
#    api_key: !secret openalr_api_key
#    region: eu
#    source:
#     - entity_id: camera.mjpeg_camera

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

map:

# Track the sun
sun:

binary_sensor:
  - platform: digital_ocean
    droplets:
      - 'do-1'
  - platform: template
    sensors:
      ha_domain_due:
        value_template: '{{ states.sensor.home_assistant < 30 }}'
        friendly_name: 'Home Assistant domain due for renewal'
  - platform: workday
    country: UK

# Weather Prediction
sensor: !include sensors.yaml

# Text to speech
tts:
  - platform: google
  - platform: microsoft
    api_key: !secret microsoft_api_key
    language: en-gb
    gender: Female
    type: Susan, Apollo
    rate: 20


config:

# camera:
#   platform: mjpeg
#   mjpeg_url: http://192.168.1.5/stream/video.mjpeg
  
mqtt:
  #broker: 172.17.0.1
  #broker: 127.0.0.1
  #port: 1883
  #client_id: home-assistant
  #username: pi
  #password: raspberry

light:
  - platform: blinkt

hue:
  bridges:
    - host: 192.168.1.16
      allow_hue_groups: false

#media_player:
#  - platform: plex

media_player:
  - platform: samsungtv
    host: 192.168.1.115
    mac: !secret samsung_tv_mac

device_tracker:
  - platform: asuswrt
    host: 192.168.1.1
    username: !secret router_username
    password: !secret router_password
    interval_seconds: 10
    consider_home: 180
    track_new_devices: no
  - platform: gpslogger

switch: !include switches.yaml

automation: !include_dir_merge_list automations/

alert:
  homeassistant_domain_renewal:
    name: Home Assistant domain due for renewal
    done_message: Home Assistant domain has been renewed
    entity_id: binary_sensor.ha_domain_due
    state: 'on'
    repeat:
      - 60 # 60 minutes
      - 1440 # 1 day
      - 2880 # every 2 days
    can_acknowledge: True
    skip_first: True
    notifiers:
      - html5

notify: !include notifiers.yaml

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

hive:
  username: !secret hive_username
  password: !secret hive_password

ifttt:
  key: !secret ifttt_key

script: !include scripts.yaml
  
digital_ocean:
  access_token: !secret digital_ocean_key

logger:
  default: info

group: !include groups.yaml

scene: !include scenes.yaml

panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: !secret home_assistant_config
    
google_assistant:
  project_id: home-assistant-184009
  client_id: !secret google_assistant_client_id
  access_token: !secret google_assistant_access_token
  agent_user_id: !secret google_agent_user_id
  api_key: !secret google_assistant_api_key
  exposed_domains:
    - switch
    
calendar:
  - platform: todoist
    token: !secret todoist_api_token
    custom_projects:
      - name: 'Due Today'
        due_date_days: 0
      - name: 'Due This Week'
        due_date_days: 7

weather: 
 - platform: darksky
   api_key: !secret darksky_api_key

#history_graph:
  #travel_time:
  #  name: Travel Time
  #  hours_to_show: 72
  #  refresh: 60
  #  entities:
   #   - sensor.time_to_home
  #    - sensor.time_to_work

 # temperatures:
  #   name: Temperature
  #    hours_to_show: 168
  #    refresh: 60
   #   entities:
   #     - sensor.hive_current_temperature
   #     - sensor.dark_sky_apparent_temperature


media_extractor:

zone:
  - name: Work
    latitude: !secret work_lat
    longitude: !secret work_long
    radius: 150
    icon: mdi:brush

xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - key: !secret xiaomi_gateway
