homeassistant: !include home_assistant.yaml

http: !include http.yaml

lovelace:
  mode: yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend: !include frontend.yaml

input_select: !include_dir_named inputs
# input_slider: !include inputs/input_slider.yaml

google:
  client_id: !secret google_calendar_client_id
  client_secret: !secret google_calendar_client_secret

# image_processing:
#  - platform: openalpr_cloud
#    api_key: !secret openalr_api_key
#    region: eu
#    source:
#     - entity_id: camera.mjpeg_camera

# Checks for available updates
#updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
# conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

map:

# Track the sun
sun:

dialogflow:

intent_script:
  GetTemperature:
    speech:
      text: The temperature at home is {{ state_attr('climate.heating', 'current_temperature') }}°c
  GetPredictionStats:
    speech:
      text: "{{ state_attr('sensor.ff1_stats', 'data').next.percentPredicted }}% of users have predicted for the {{ state_attr('sensor.ff1_stats', 'data').next.name }}"
  GetPayDay:
    speech:
      text: "Pay day is {{ states('sensor.pay_day') }}"

binary_sensor:
  - platform: digital_ocean
    droplets:
      - 'do-1'
  - platform: template
    sensors:
      ha_domain_due:
        value_template: "{{ (states('sensor.home_assistant')|int) < 30 }}"
        friendly_name: 'Home Assistant domain due for renewal'
  - platform: workday
    country: UK
  - platform: bayesian
    name: Sophie arrived home
    prior: 0.1
    observations:
      - entity_id: 'device_tracker.oneplus_6'
        prob_given_true: 0.7
        prob_given_false: 0.2
        platform: 'state'
        to_state: 'home'
      - entity_id: 'binary_sensor.door_window_sensor_158d0002253f18'
        platform: 'state'
        to_state: 'on'
        prob_given_true: 0.6
        prob_given_false: 0.2

# Weather Prediction
sensor: !include sensors.yaml

camera: !include cameras.yaml

# Text to speech
tts:
  - platform: google
  - platform: microsoft
    api_key: !secret microsoft_api_key
    language: en-gb
    gender: Female
    type: Susan, Apollo
    rate: 20

config:

mqtt:
  discovery: true
  discovery_prefix: homeassistant
  broker: 127.0.0.1
  client_id: home-assistant
  port: 1883

light:
  - platform: group
    name: Bathroom Lights
    entities:
      - light.bathroom_light_1
      - light.bathroom_light_2
      - light.bathroom_light_3
  - platform: group
    name: Kitchen Lights
    entities:
      - light.kitchen_light_1
      - light.kitchen_light_2
      - light.kitchen_light_3
      - light.kitchen_light_4
      - light.kitchen_table
  - platform: mqtt
    name: Cupboard
    schema: json
    command_topic: !secret anavi_channel
    brightness: true
    rgb: true
    retain: true
    effect: true
    brightness_scale: 4095
  - platform: yeelight
    devices:
      192.168.1.219:
        name: Bedside

hue:
  bridges:
    - host: 192.168.1.16
      allow_hue_groups: false
      allow_unreachable: true

#media_player:
#  - platform: plex

media_player:
  - platform: samsungtv
    host: 192.168.1.115
    mac: !secret samsung_tv_mac
  - platform: spotify
    client_id: !secret spotify_client_id
    client_secret: !secret spotify_client_secret

device_tracker:
  - platform: asuswrt
    host: 192.168.1.1
    username: !secret router_username
    password: !secret router_password
    interval_seconds: 10
    consider_home: 180
    track_new_devices: no

asuswrt:
    host: 192.168.1.1
    username: !secret router_username
    password: !secret router_password

switch: !include switches.yaml

automation: !include_dir_merge_list automations/

alert:
  homeassistant_domain_renewal:
    name: Home Assistant domain due for renewal
    done_message: Home Assistant domain has been renewed
    entity_id: binary_sensor.ha_domain_due
    state: 'on'
    repeat:
      - 60 # 60 minutes
      - 1440 # 1 day
      - 2880 # every 2 days
    can_acknowledge: True
    skip_first: True
    notifiers:
      - html5

notify: !include notifiers.yaml

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

hive:
  username: !secret hive_username
  password: !secret hive_password

ifttt:
  key: !secret ifttt_key

script: !include_dir_named scripts
  
digital_ocean:
  access_token: !secret digital_ocean_key

logger:
  default: warning

group: !include groups.yaml

scene: !include scenes.yaml
    
google_assistant:
  project_id: edson-home
  api_key: !secret google_assistant_api_key
  exposed_domains:
    - switch
    - light
    - climate
  entity_config:
    light.cupboard:
      name: Cupboard lights
      aliases:
        - Kitchen Counter Lights
        - Coloured Lights
      expose: true
    light.bathroom_lights:
      expose: false
    light.kitchen_lights:
      expose: false

#calendar:
#  - platform: todoist
#    token: !secret todoist_api_token
#    custom_projects:
#      - name: 'Due Today'
#        due_date_days: 0
#      - name: 'Due This Week'
#        due_date_days: 7

weather: 
 - platform: darksky
   api_key: !secret darksky_api_key

#history_graph:
  #travel_time:
  #  name: Travel Time
  #  hours_to_show: 72
  #  refresh: 60
  #  entities:
   #   - sensor.time_to_home
  #    - sensor.time_to_work

 # temperatures:
  #   name: Temperature
  #    hours_to_show: 168
  #    refresh: 60
   #   entities:
   #     - sensor.hive_current_temperature
   #     - sensor.dark_sky_apparent_temperature


media_extractor:

zone:
  - name: Work
    latitude: !secret work_lat
    longitude: !secret work_long
    radius: 150
    icon: mdi:brush

xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - key: !secret xiaomi_gateway
      mac: '78:11:DC:B2:5E:74'

alarm_control_panel:
  - platform: manual
    name: House Alarm
    code: !secret alarm_code
    delay_time: 30
    armed_home:
      pending_time: 0
      delay_time: 0

#homekit:
#  filter:
#    include_domains:
#      - alarm_control_panel
#      - light
#      - switch

influxdb:
  host: !secret influx_host
  port: 443
  username: !secret influx_username
  password: !secret influx_password  
  
duckdns:
  domain: !secret duck_dns_domain
  access_token: !secret duck_dns_token

recorder:
  purge_keep_days: 10
  db_url: !secret db_url
