hassio:

homeassistant: !include home_assistant.yaml

http: !include http.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend: !include frontend.yaml

input_select: !include inputs/input_select.yaml
# input_slider: !include inputs/input_slider.yaml

shell_command: !include shell_commands.yaml


# image_processing:
#  - platform: openalpr_cloud
#    api_key: !secret openalr_api_key
#    region: eu
#    source:
#     - entity_id: camera.mjpeg_camera

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

map:

# Track the sun
sun:

binary_sensor:
  - platform: digital_ocean
    droplets:
      - 'do-1'

# Weather Prediction
sensor: !include sensors.yaml

# Text to speech
tts:
  platform: google

config:

# camera:
#   platform: mjpeg
#   mjpeg_url: http://192.168.1.5/stream/video.mjpeg
  
mqtt:
  #broker: 172.17.0.1
  #broker: 127.0.0.1
  #port: 1883
  #client_id: home-assistant
  #username: pi
  #password: raspberry

light:
  - platform: blinkt

hue:
  bridges:
    - host: 192.168.1.16
      allow_hue_groups: false

#media_player:
#  - platform: plex

media_player:
  - platform: samsungtv
    host: 192.168.1.115
    mac: !secret samsung_tv_mac

device_tracker:
  - platform: asuswrt
    host: 192.168.1.1
    username: !secret router_username
    password: !secret router_password
    interval_seconds: 10
    consider_home: 180
    track_new_devices: no

switch: !include switches.yaml

automation: !include_dir_merge_list automations/

notify: !include notifiers.yaml

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

hive:
  username: !secret hive_username
  password: !secret hive_password

ifttt:
  key: !secret ifttt_key

script: !include scripts.yaml
  
digital_ocean:
  access_token: !secret digital_ocean_key

logger:
  default: info

group: !include groups.yaml

scene: !include scenes.yaml

panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: !secret home_assistant_config
    
google_assistant:
  project_id: home-assistant-184009
  client_id: !secret google_assistant_client_id
  access_token: !secret google_assistant_access_token
  agent_user_id: !secret google_agent_user_id
  api_key: !secret google_assistant_api_key
  exposed_domains:
    - switch
    
calendar:
  - platform: todoist
    token: !secret todoist_api_token
    custom_projects:
      - name: 'Due Today'
        due_date_days: 0
      - name: 'Due This Week'
        due_date_days: 7

weblink: 
  entities: 
    - name: Router 
      url: http://192.168.1.1/
      icon: mdi:router-wireless

