- platform: group
  name: Hall Lights
  entities:
    - light.porch
    - light.gateway_light_7811dcb25e74

- platform: switch
  name: Mini Lights
  entity_id: switch.32002710bcddc226b4b0

- platform: switch
  name: Bonsai Lights
  entity_id: switch.bf4cadf5e3e38fddf078v2

# - platform: mqtt
#   name: Cupboard
#   schema: json
#   command_topic: !secret anavi_channel
#   brightness: true
#   rgb: true
#   retain: true
#   effect: true
#   brightness_scale: 4095

- platform: group
  name: Bedroom Spotlights
  entities:
    - light.bedroom_light_1
    - light.bedroom_light_2
    - light.bedroom_light_3
    - light.bedroom_light_4
    - light.bedroom_light_5
    - light.bedroom_light_6

- platform: group
  name: Bedroom Reading Lights
  entities:
    - light.bedroom_light_lb
    - light.bedroom_light_rb
    - light.bedside_light_lt
    - light.bedside_light_rt

- platform: group
  name: Bedroom Lights
  entities:
    - light.bedroom_spotlights
    - light.bedroom_reading_lights

- platform: group
  name: Kitchen Lights
  entities:
    - light.shelly_b
    - light.shelly_c

- platform: yeelight
  devices:
    192.168.1.219:
      name: Bedside
      model: bslamp1
      save_on_change: true
  custom_effects:
    - name: 'Fire Flicker'
      flow_params:
        count: 0
        transitions:
          - TemperatureTransition: [1900, 1000, 80]
          - TemperatureTransition: [1900, 2000, 60]
          - SleepTransition:       [1000]
