- platform: group
  name: Hall Lights
  entities:
    - light.porch
    - light.gateway_light_7811dcb25e74

- platform: switch
  name: Mini Lights
  entity_id: switch.32002710bcddc226b4b0

- platform: switch
  name: Bonsai Lights
  entity_id: switch.bf4cadf5e3e38fddf078v2

# - platform: mqtt
#   name: Cupboard
#   schema: json
#   command_topic: !secret anavi_channel
#   brightness: true
#   rgb: true
#   retain: true
#   effect: true
#   brightness_scale: 4095

- platform: group
  name: Bedroom Reading Lights
  entities:
    - light.bedroom_light_lb
    - light.bedroom_light_rb
    - light.bedside_light_lt
    - light.bedside_light_rt

- platform: group
  name: Lounge Lights
  entities:
    - light.twigs_light
    - light.lounge_tall_lamp_light
    - light.mini_lights
    - light.bonsai_lights
    - light.lounge_spotlight_light

- platform: group
  name: Conservatory Lights
  entities:
    - light.table_light_1_light
    - light.table_light_2_light
    - light.table_light_3_light
    - light.hanging_light_1_light
    - light.hanging_light_2_light
    - light.wled

- platform: group
  name: Kitchen Lights
  entities:
    - light.shelly_b
    - light.shelly_c

- platform: mqtt
  name: "Bedroom Spotlights"
  schema: json
  command_topic: "zigbee2mqtt/bedroom_lights/set"
  state_topic: "zigbee2mqtt/bedroom_lights"
  color_temp: false
  brightness: true

- platform: yeelight
  devices:
    192.168.1.219:
      name: Bedside
      model: bslamp1
      save_on_change: true
  custom_effects:
    - name: 'Fire Flicker'
      flow_params:
        count: 0
        transitions:
          - TemperatureTransition: [1900, 1000, 80]
          - TemperatureTransition: [1900, 2000, 60]
          - SleepTransition:       [1000]
