- platform: group
  name: Hall Lights
  entities:
    - light.porch
    - light.gateway_light_7811dcb25e74

- platform: switch
  name: Mini Lights
  entity_id: switch.32002710bcddc226b4b0

- platform: switch
  name: Bonsai Lights
  entity_id: switch.bf4cadf5e3e38fddf078v2

# - platform: mqtt
#   name: Cupboard
#   schema: json
#   command_topic: !secret anavi_channel
#   brightness: true
#   rgb: true
#   retain: true
#   effect: true
#   brightness_scale: 4095

- platform: group
  name: Porch Lights
  entities:
    - light.porch_light_1
    - light.porch_light_2

- platform: group
  name: Bedroom Reading Lights
  entities:
    - light.bedroom_light_lb
    - light.bedroom_light_lt
    - light.bedroom_light_rb
    - light.bedroom_light_rt

- platform: group
  name: Garden Lights
  entities:
    - light.garden_light_1
    - light.garden_light_2
    - light.garden_light_3
    - light.garden_light_4

- platform: group
  name: Lounge Lights
  entities:
    # - light.hue_play_left
    # - light.hue_play_right
    - light.orb
    - light.lounge_tall_lamp
    # - light.lounge_spotlight

- platform: group
  name: Conservatory Lights
  entities:
    - light.table_light_1
    - light.table_light_2
    - light.table_light_3
    - light.hanging_light_1
    - light.hanging_light_2
    - light.wled

- platform: group
  name: Bedroom Ceiling
  entities:
    - light.bedroom_light_1
    - light.bedroom_light_2
    - light.bedroom_light_3
    - light.bedroom_light_4
    - light.bedroom_light_5
    - light.bedroom_light_6

- platform: group
  name: Kitchen Lights
  entities:
    - light.shelly_b
    - light.shelly_c

- platform: group
  name: Kitchen All
  entities:
    - light.shelly_b
    - light.shelly_c
    - light.table_light_1
    - light.table_light_2
    - light.table_light_3
    - light.hanging_light_1
    - light.hanging_light_2
    - light.wled

#- platform: mqtt
#  name: "Bedroom Spotlights"
#  schema: json
#  command_topic: "zigbee2mqtt/bedroom_lights/set"
#  state_topic: "zigbee2mqtt/bedroom_lights"
#  color_temp: false
#  brightness: true
