# - platform: group
#   name: Bathroom Lights
#   entities:
#     - light.bathroom_light_1
#     - light.bathroom_light_2
#     - light.bathroom_light_3

- platform: group
  name: Kitchen Lights
  entities:
    # - light.kitchen_light_1
    # - light.kitchen_light_2
    # - light.kitchen_light_3
    # - light.kitchen_light_4
    - light.kitchen_table

- platform: group
  name: Hall Lights
  entities:
    - light.landing_light
    - light.porch
    - light.gateway_light_7811dcb25e74

# - platform: mqtt
#   name: Cupboard
#   schema: json
#   command_topic: !secret anavi_channel
#   brightness: true
#   rgb: true
#   retain: true
#   effect: true
#   brightness_scale: 4095

- platform: group
  name: Bedroom Lights
  entities:
    - light.bedroom_light_1
    - light.bedroom_light_2
    - light.bedroom_light_3
    - light.bedroom_light_4
    - light.bedroom_light_5
    - light.bedroom_light_6


- platform: yeelight
  devices:
    192.168.1.219:
      name: Bedside
      model: bslamp1
      save_on_change: true
  custom_effects:
    - name: 'Fire Flicker'
      flow_params:
        count: 0
        transitions:
          - TemperatureTransition: [1900, 1000, 80]
          - TemperatureTransition: [1900, 2000, 60]
          - SleepTransition:       [1000]
