- platform: group
  name: Hall Lights
  entities:
    - light.porch
    - light.gateway_light_7811dcb25e74

- platform: switch
  name: Mini Lights
  entity_id: switch.32002710bcddc226b4b0

- platform: switch
  name: Bonsai Lights
  entity_id: switch.bf4cadf5e3e38fddf078v2

# - platform: mqtt
#   name: Cupboard
#   schema: json
#   command_topic: !secret anavi_channel
#   brightness: true
#   rgb: true
#   retain: true
#   effect: true
#   brightness_scale: 4095

- platform: group
  name: Porch Lights
  entities:
    - light.porch_light_1_light
    - light.porch_light_2_light

- platform: group
  name: Bedroom Reading Lights
  entities:
    - light.bedroom_light_lb_light
    - light.bedroom_light_lt_light
    - light.bedroom_light_rb_light
    - light.bedroom_light_rt_light

- platform: group
  name: Garden Lights
  entities:
    - light.garden_light_1_light
    - light.garden_light_2_light
    - light.garden_light_3_light
    - light.garden_light_4_light

- platform: group
  name: Lounge Lights
  entities:
    - light.twigs_light
    - light.lounge_tall_lamp_light
    - light.mini_lights
    - light.bonsai_lights
    - light.lounge_spotlight_light

- platform: group
  name: Conservatory Lights
  entities:
    - light.table_light_1_light
    - light.table_light_2_light
    - light.table_light_3_light
    - light.hanging_light_1_light
    - light.hanging_light_2_light
    - light.wled

- platform: group
  name: Bedroom Ceiling
  entities:
    - light.bedroom_light_1_light
    - light.bedroom_light_2_light
    - light.bedroom_light_3_light
    - light.bedroom_light_4_light
    - light.bedroom_light_5_light
    - light.bedroom_light_6_light

- platform: group
  name: Kitchen Lights
  entities:
    - light.shelly_b
    - light.shelly_c

- platform: mqtt
  name: "Bedroom Spotlights"
  schema: json
  command_topic: "zigbee2mqtt/bedroom_lights/set"
  state_topic: "zigbee2mqtt/bedroom_lights"
  color_temp: false
  brightness: true
