- platform: steam_online
  api_key: !secret steam_api_key
  accounts:
    - !secret steam_account_id

- platform: fitbit
  monitored_resources:
    - "body/weight"
    - "activities/steps"
    - "activities/heart"
    - "devices/battery"

- platform: pi_hole
  host: 192.168.1.193

- platform: speedtest
  monitored_conditions:
    - ping
    - download
    - upload
  minute:
    - 0
    - 30

- platform: darksky
  api_key: !secret darksky_api_key
  monitored_conditions:
    - summary
    - nearest_storm_distance
    - apparent_temperature
    - minutely_summary

- platform: command_line
  name: CPU Temperature
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  # If errors occur, remove degree symbol below
  unit_of_measurement: "°C"
  value_template: '{{ value | multiply(0.001) }}'

- platform: whois
  domain: steveedson.co.uk
  name: SteveEdson.co.uk

- platform: whois
  domain: !secret base_url
  name: Home Assistant

- platform: whois
  domain: fantasyformula1.co.uk
  name: FantasyFormula1.co.uk

#- platform: google_travel_time
#  name: Time to Work
#  api_key: !secret google_assistant_api_key
#  origin: !secret home_address
#  destination: !secret work_address

#- platform: google_travel_time
#  name: Time to Home
#  api_key: !secret google_assistant_api_key
#  origin: !secret work_address
#  destination: !secret home_address
  
- platform: cert_expiry
  name: SteveEdson.co.uk SSL 
  host: steveedson.co.uk
 
- platform: cert_expiry 
  host: fantasyformula1.co.uk
  name: FantasyFormula1.co.uk SSL

- platform: cert_expiry
  host: !secret base_url
  name: Home Assistant SSL