- platform: wake_on_lan
  mac: !secret pc_mac
  name: Aegis
  host: 192.168.1.125

#- platform: broadlink
#  host: 192.168.1.168
#  mac: !secret broadlink_mac
#  friendly_name: 'Broadlink'
#  timeout: 15
#  type: 'rm_mini'
#  switches:
#    surround_sound:
#      friendly_name: Surround Sound
#      command_on: 'JgBQAAABKJMTEhQREhMTNxITExITEhITEjgSOBM3EhMSOBM3EjcTOBISFRESExISFTYUEBMTEhMSNxM3EzgUNRIUEzYSOBM4EwAFIAABKUgVAA0FAAAAAAAAAAA='
#      command_off: 'JgBQAAABKJMTEhQREhMTNxITExITEhITEjgSOBM3EhMSOBM3EjcTOBISFRESExISFTYUEBMTEhMSNxM3EzgUNRIUEzYSOBM4EwAFIAABKUgVAA0FAAAAAAAAAAA='

- platform: template
  switches:
    aegis_pc:
      friendly_name: "Aegis"
      value_template: "{{ is_state('binary_sensor.aegis_connected', 'on') }}"
      turn_on:
        service: script.turn_on_pc
      turn_off:
        service: script.shutdown_pc
      icon_template: mdi:desktop-tower-monitor
