title: Edson Home
resources:
  - url: /local/custom_ui/card-tools.js?v=2
    type: js
  - url: /local/custom_ui/auto-entities.js?v=1.5
    type: js
  - url: /local/custom_ui/bar-card.js?v=2
    type: js
  - url: /local/custom_ui/mini-graph-card-bundle.js?v=0.5.0
    type: module
  - url: /local/custom_ui/mini-media-player-bundle.js?v=1.2.2
    type: module
  - url: /local/custom_ui/unused-card.js?v=0.2
    type: module
  - url: /local/custom_ui/simple-weather-card-bundle.js?v=0.5.0
    type: module
  - url: /local/custom_ui/slider-entity-row.js?v=8
    type: module
  - url: /local/custom_ui/gui-sandbox.js
    type: module
  - url: /local/custom_ui/plan-coordinates.js
    type: module
  - url: /local/custom_ui/xiaomi-vacuum-card.js?v=2.3.2
    type: js
  - url: /local/custom_ui/layout-card.js
    type: module

views:
  - icon: mdi:home-assistant
    path: home
    # Name of the view. Will be used as the tooltip for tab icon
    title: Home
    cards:
      - type: alarm-panel
        entity: alarm_control_panel.house_alarm
      - type: thermostat
        entity: climate.netatmo_heating
        name: Heating
      - type: map
        aspect_ratio: 16:9
        default_zoom: 14
        entities:
          - device_tracker.steveedson_oneplus5t

  - icon: mdi:stairs
    path: hallway
    badges:
      - binary_sensor.door_window_sensor_158d00035c0b6e
    # Name of the view. Will be used as the tooltip for tab icon
    title: Hallway
    cards:
      - type: light
        entity: light.shelly_a
      - type: picture-elements
        image: /local/nest.jpg
        elements:
          - type: state-icon
            entity: sensor.living_room_nest_protect_battery_health
            style:
              top: 50%
              left: 30%
          - type: state-icon
            entity: sensor.living_room_nest_protect_co_status
            style:
              top: 50%
              left: 40%
          - type: state-icon
            entity: binary_sensor.living_room_nest_protect_online
            style:
              top: 50%
              left: 50%
          - type: state-icon
            entity: sensor.living_room_nest_protect_smoke_status
            style:
              top: 50%
              left: 60%
          - type: state-icon
            entity: sensor.living_room_nest_protect_color_status
            style:
              top: 50%
              left: 70%
      - type: entity-button
        entity: script.find_phone

  - icon: mdi:sofa
    title: Lounge
    path: lounge
    cards:
      - type: plant-status
        entity: plant.sunflower
        name: Lounge Plant

      - type: vertical-stack
        cards:
          - type: custom:mini-media-player
            entity: media_player.lounge_tv
            icon: mdi:television
            artwork: cover
            hide:
              volume: false
              source: true
              power_state: false

          - type: custom:mini-media-player
            entity: media_player.playstation_4
            icon: mdi:playstation
            artwork: cover
            hide:
              volume: true
              source: true
              power_state: false
              controls: true

      - type: glance
        show_state: false
        entities:
          - entity: scene.bright
            tap_action:
              action: call-service
              service: scene.turn_on
              service_data:
                entity_id: scene.bright

          - entity: scene.deep_blue
            tap_action:
              action: call-service
              service: scene.turn_on
              service_data:
                entity_id: scene.deep_blue

          - entity: scene.ocean
            tap_action:
              action: call-service
              service: scene.turn_on
              service_data:
                entity_id: scene.ocean

          - entity: scene.lounge_lights_off
            name: Lights Off
            tap_action:
              action: call-service
              service: scene.turn_on
              service_data:
                entity_id: scene.lounge_lights_off

      - type: entities
        entities:
          - type: custom:slider-entity-row
            entity: light.left_lamp
            toggle: true
          - type: custom:slider-entity-row
            entity: light.twigs
            toggle: true
          - type: custom:slider-entity-row
            entity: light.corner_lamp
            toggle: true

  - icon: mdi:toggle-switch
    title: Active Devices
    path: active
    cards:
      - type: custom:auto-entities
        card:
          type: entities
          title: Active Devices
        filter:
          include:
            - state: "on"
              domain: /media_player|light/

  - icon: mdi:kettle
    title: Kitchen
    path: kitchen
    badges:
      - binary_sensor.door_window_sensor_158d00035c0c9a
    cards:
      - type: custom:xiaomi-vacuum-card
        entity: vacuum.xiaomi_vacuum_cleaner
        image: /local/vacuum.png
        name: false
        buttons: true

      - type: entities
        entities:
          - light.shelly_b
          - light.shelly_c
        title: Lights
        show_header_toggle: true

      - type: entities
        entities:
          - sensor.bin_days

      - type: custom:mini-graph-card
        entities:
          - sensor.house_temperature
          - sensor.dark_sky_apparent_temperature

      - type: vertical-stack
        cards:
          - type: custom:mini-media-player
            entity: media_player.downstairs
            icon: mdi:spotify
            artwork: cover
            hide:
              volume: false
              source: true
              power_state: false
            shortcuts:
              columns: 4 # Max buttons per row
              buttons:
                # Start predefined playlist
                - icon: mdi:radio
                  type: script
                  id: script.play_radio_in_kitchen

          - type: custom:mini-media-player
            entity: media_player.kitchen_max
            icon: mdi:spotify
            artwork: cover
            hide:
              volume: true
              source: true
              power_state: false

          - type: custom:mini-media-player
            entity: media_player.kitchen_display
            icon: mdi:spotify
            artwork: cover
            hide:
              volume: true
              source: true
              power_state: false

      - type: custom:mini-media-player
        entity: media_player.kitchen_tv
        icon: mdi:television
        artwork: cover
        hide:
          volume: true
          source: true
          power_state: false

      - type: thermostat
        entity: climate.netatmo_heating
        name: Heating

  - path: outside
    icon: mdi:tree
    title: Outside
    cards:
      - type: entities
        entities:
          - sensor.bin_days
          - sensor.next_bus_to_town
      - type: picture-glance
        title: Camera
        entities:
          - person.steve_edson
        camera_image: camera.g3_flex
      - type: custom:simple-weather-card
        entity: weather.dark_sky
        name: "at home"
        backdrop: true
# todo: add hot tub temp eventually

  - path: bedroom
    icon: mdi:hotel
    title: Bedroom
    cards:
      - type: glance
        show_state: false
        columns: 3
        entities:
          - entity: scene.bedroom_reading
            name: Reading
            tap_action:
              action: call-service
              service: scene.turn_on
              service_data:
                entity_id: scene.bedroom_reading

          - entity: scene.bedroom_steve_reading
            name: Steve Reading
            tap_action:
              action: call-service
              service: scene.turn_on
              service_data:
                entity_id: scene.bedroom_steve_reading

          - entity: scene.bedroom_off
            name: "Off"
            tap_action:
              action: call-service
              service: scene.turn_on
              service_data:
                entity_id: scene.bedroom_off

      - type: entities
        entities:
          - type: custom:slider-entity-row
            entity: light.bedroom_spotlights
            toggle: true
          - type: custom:slider-entity-row
            entity: light.bedroom_reading_lights
            toggle: true
          - type: custom:slider-entity-row
            entity: light.yeelight_bslamp1_7c49eb28d971
            toggle: true
      - type: custom:mini-media-player
        entity: media_player.bedroom_android_tv
        icon: mdi:television
        artwork: cover
        hide:
          volume: false
          source: false
          power_state: false
      - type: custom:mini-media-player
        entity: media_player.bedroom_speaker
        icon: mdi:spotify
        artwork: cover
        hide:
          volume: false
          source: true
          power_state: true
#        shortcuts:
#          columns: 4 # Max buttons per row
#          buttons:
#            # Start predefined playlist
#            - icon: mdi:radio
#              type: script
#              id: script.play_radio_in_office

  - icon: mdi:office-building
    path: homeoffice
    cards:
      - type: custom:mini-media-player
        entity: media_player.home_office_speaker
        icon: mdi:spotify
        artwork: cover
        hide:
          volume: false
          source: true
          power_state: true
        shortcuts:
          columns: 4 # Max buttons per row
          buttons:
            # Start predefined playlist
            - icon: mdi:radio
              type: script
              id: script.play_radio_in_office
      - type: light
        entity: light.office
      - type: thermostat
        entity: climate.home_office

  - icon: mdi:music-box
    path: media
    title: Media
    panel: true
    cards:
      - type: custom:auto-entities
        max_columns: 3
        filter:
          include:
            - domain: media_player
              options:
                type: custom:mini-media-player # Make sure to specify a card type for every filter
        sort:
          method: name
          ignore_case: true
        card:
          type: custom:layout-card

  - path: office
    title: Office
    icon: mdi:google-controller
    cards:
      - type: entity-button
        entity: switch.aegis
      - type: entities
        entities:
          - sensor.steam_76561198059721761
        title: Steam
        show_header_toggle: false

  - path: Unused
    title: Unused
    cards:
      - type: custom:gui-sandbox
      - type: custom:unused-card

  - path: system
    title: System
    cards:
      - type: entities
        entities:
          - sensor.speedtest_download
          - sensor.speedtest_ping
          - sensor.speedtest_upload
          - binary_sensor.do_1
          - sensor.rt_ac68u_bytes_received
          - sensor.rt_ac68u_bytes_sent
          - sensor.rt_ac68u_kbyte_sec_received
          - sensor.rt_ac68u_kbyte_sec_sent
          - sensor.rt_ac68u_packets_received
          - sensor.rt_ac68u_packets_sent
          - sensor.rt_ac68u_packets_sec_received
          - sensor.rt_ac68u_packets_sec_sent
        title: Network Stats
        show_header_toggle: true
      - type: entities
        entities:
          - sensor.disk_free
          - sensor.load_5m
          - sensor.memory_free
          - sensor.latest_version
          - sensor.current_version
        title: Home Assistant
        show_header_toggle: true
