title: The Paddocks
views: !include_dir_list ui-lovelace/

custom_header:
  compact_mode: true
  hide_config: true
  footer_mode: false
  background: var(--app-header-background-color)
  elements_color: var(--app-header-text-color)
  active_tab_color: var(--state-icon-active-color)
  tab_indicator_color: var(--state-icon-active-color)
