resources:
  - url: /local/custom_ui/weather-card.js
    type: js

title: Edson Home
views:
  - icon: mdi:home-assistant
    id: home
    # Name of the view. Will be used as the tooltip for tab icon
    title: Home
    cards:
      - type: picture-elements
        title: Main Level
        image: https://steveedson.co.uk/floorplan.png
        elements:
          - type: service-button
            title: Lights Off
            style:
              top: 95%
              right: 1%
              padding: 0px
            service: light.turn_off
            service_data:
              entity_id: group.all_lights
          - type: state-icon
            entity: light.bathroom_light_1
            tap_action: toggle
            style:
              top: 80%
              left: 87%
          - type: state-icon
            entity: light.light.landing_light
            tap_action: toggle
            style:
              top: 55%
              left: 87%
#      - type: glance
#        title: Doors
#        entities:
#          - binary_sensor.back_door
#          - binary_sensor.front_door
#          - entity: binary_sensor.door_window_sensor_158d0001bf26df
#            title: Garage
#          - entity: binary_sensor.ring_front_door_motion
#            title: Front Motion
#      - type: entity-filter
#        filter:
#          - domain: light
#            state: 'on'
#          - domain: light
#            state: 'off'
#          - entity_id: switch.driveway
#          - entity_id: switch.wemoporch
#        card:
#          title: Lights
#      - type: entities
#        title: Switches
#        entities:
#          - switch.wemoswitch
#          - switch.garage_relay_switch
#          - switch.wemoinsight
#      - type: entities
#        title: Ring Doorbell
#        entities:
#          - binary_sensor.ring_front_door_ding
#          - binary_sensor.ring_front_door_motion
#          - sensor.ring_front_door_last_activity
#          - sensor.ring_front_door_last_ding
#          - sensor.ring_front_door_last_motion
