- platform: rest
  resource: !secret google_holiday_sheet
  name: Holiday allowance remaining this year
  value_template: '{{ value_json.feed.entry[0]["gsx$allowanceremaining"]["$t"] }}'
  unit_of_measurement: days
  scan_interval: 7200

- platform: rest
  resource: !secret google_holiday_sheet
  name: Holiday's not yet taken
  value_template: '{{ value_json.feed.entry[0]["gsx$futureholidays"]["$t"] }}'
  unit_of_measurement: days
  scan_interval: 7200

- platform: rest
  resource: !secret google_holiday_sheet
  name: Next Holiday
  value_template: '{{ value_json["Next Holiday"] }}'
  json_attributes:
    - "Holiday Year"
    - "Allowance"
    - "Days booked"
    - "Allowance remaining"
    - "Days Till Next Holiday"
  scan_interval: 7200

- platform: rest
  resource: !secret ff1_stats_url
  name: FF1 Stats
  value_template: '{{ value_json.data.next.name }} - {{ value_json.data.next.percentPredicted }}% Predicted'
  json_attributes:
    - data
  scan_interval: 7200

- platform: rest
  resource: !secret bins_api
  name: Bin days
  value_template: >
    {% if value_json.success %}
    {% set numSeconds = (as_timestamp(strptime(value_json.date, "%d/%m/%Y")) | float) - (as_timestamp(now()) | float) %}{{ value_json.bins }} in {{ (numSeconds / 60 / 60 / 24) | round }} days
    {% else %}
    Bin data not available
    {% endif %}
  json_attributes:
    - date
    - bins
    - image
  scan_interval: 7200

- platform: rest
  resource: !secret pay_day_api
  name: Pay Day
  value_template: '{{ value_json.daysRemaining }} days remaining'
  json_attributes:
    - daysRemaining
    - isToday
    - payday
    - unix
  scan_interval: 7200
