- platform: sql
  db_url: !secret db_url
  queries:
    - name: Bottle Warmer Last On
      query: >
        select * from states
        where entity_id = "switch.bff5c4bbd438ed9847uxkj" and state = "on"
        order by last_updated DESC
        LIMIT 1
      column: 'last_changed'