- platform: systemmonitor
  resources:
    - type: disk_free
      arg: /
    - type: memory_free
    - type: load_5m

- platform: version
  source: local

- platform: version
  source: docker
  
- platform: statistics
  name: Hot Tub Stats
  entity_id: sensor.hot_tub_temperature
  max_age:
    hours: 1
    