- platform: version
  source: local

- platform: version
  source: docker

- platform: statistics
  name: Hot Tub Stats
  state_characteristic: mean
  entity_id: sensor.hot_tub_temperature
  max_age:
    hours: 1
