- platform: template
  sensors:
    # race_deadline_day:
    #   friendly_name: "Race Deadline Day"
    #   value_template: "{{ False }}"

    house_temperature:
      friendly_name: "House Temperature"
      unit_of_measurement: '°C'
      value_template: "{{ float(states.climate.hallway.attributes.current_temperature) }}"

    sun_elevation:
      friendly_name: Sun Elevation
      unit_of_measurement: '°'
      value_template: "{{ states.sun.sun.attributes.elevation | float }}"
#
#    detected_objects:
#      friendly_name: "Detected Objects"
#      value_template: "{% if states.image_processing.doods_g3_flex_low_res %}{{ states.image_processing.doods_g3_flex_low_res.attributes.matches|length }}: {{ states.image_processing.doods_g3_flex_low_res.attributes.matches.keys()|list|join(', ')}}{% else %}Nothing{% endif %}"

- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'
