- platform: template
  sensors:
    # race_deadline_day:
    #   friendly_name: "Race Deadline Day"
    #   value_template: "{{ False }}"

    house_temperature:
      friendly_name: "House Temperature"
      unit_of_measurement: '°C'
      value_template: "{{ float(states.climate.hallway.attributes.current_temperature) }}"

    sun_elevation:
      friendly_name: Sun Elevation
      unit_of_measurement: '°'
      value_template: "{{ states.sun.sun.attributes.elevation | float }}"
#

    330i_mileage_miles:
      friendly_name: "330i mileage (miles)"
      unit_of_measurement: 'mi'
      value_template: "{{ ((states.sensor['330i_mileage'].state | float) * 0.621371) | round }}"


    330i_remaining_range_fuel_miles:
      friendly_name: "330i remaining range (miles)"
      unit_of_measurement: 'mi'
      value_template: "{{ ((states.sensor['330i_remaining_range_fuel'].state | float) * 0.621371) | round }}"

- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'
