- platform: whois
  domain: fantasyformula1.co.uk
  name: FantasyFormula1.co.uk

- platform: whois
  domain: !secret base_domain
  name: Home Assistant

- platform: whois
  domain: steveedson.co.uk
  name: SteveEdson.co.uk
