- platform: mqtt
  name: "Aegis - Connected"
  state_topic: "iotlink/workgroup/my-computer/lwt"
  value_template: "{{ value }}"
  payload_on: "ON"
  payload_off: "OFF"
  device_class: "connectivity"
  qos: 1

- platform: mqtt
  name: "Aegis - Charging"
  state_topic: "iotlink/workgroup/my-computer/windows-monitor/stats/power/status"
  value_template: "{{ value }}"
  payload_on: "Online"
  payload_off: "Offline"
  device_class: "plug"
  availability_topic: "iotlink/workgroup/my-computer/lwt"
  payload_available: "ON"
  payload_not_available: "OFF"
  qos: 1

- platform: mqtt
  name: "Aegis - Battery Status"
  state_topic: "iotlink/workgroup/my-computer/windows-monitor/stats/battery/status"
  value_template: "{{ value }}"
  payload_on: "Online"
  payload_off: "Offline"
  device_class: "plug"
  availability_topic: "iotlink/workgroup/my-computer/lwt"
  payload_available: "ON"
  payload_not_available: "OFF"
  qos: 1
