- platform: mqtt
  name: "Aegis - Connected"
  state_topic: "iotlink/workgroup/desktop-b4rim5c/lwt"
  value_template: "{{ value }}"
  payload_on: "ON"
  payload_off: "OFF"
  device_class: "connectivity"
  qos: 1
