- platform: template
  sensors:
    ha_domain_due:
      value_template: "{{ (states('sensor.home_assistant')|int) < 30 }}"
      friendly_name: 'Home Assistant domain due for renewal'
    ha_latest_version:
      value_template: "{{ states('sensor.current_version') == states('sensor.latest_version') }}"
      friendly_name: 'Home Assistant Latest Version'
