- platform: template
  sensors:
    ha_domain_due:
      value_template: "{{ (states('sensor.home_assistant')|int) < 30 }}"
      friendly_name: 'Home Assistant domain due for renewal'
    ha_latest_version:
      value_template: "{{ states('sensor.current_version') == states('sensor.latest_version') }}"
      friendly_name: 'Home Assistant Latest Version'
    activate_motion_lights:
      friendly_name: Activate Motion Lights?
      value_template: >
        {% if states('binary_sensor.night') == 'on' or states('sensor.sun_elevation')|float < 12 %}
        true
        {% else %}
        false
        {% endif %}
