- platform: trend
  sensors:
    hot_tub_heating:
      entity_id: sensor.cpu_speed
      sensor_duration: 300
      device_class: heat

    hot_tub_cooling:
      entity_id: sensor.cpu_speed
      sensor_duration: 300
      device_class: cold
      invert: true