- alias: 'Alarm triggered actions'
  trigger:
    - platform: state
      entity_id: alarm_control_panel.house_alarm
      to: 'triggered'
  action:
    - service: notify.home_assistant
      data_template:
        message: 'The house alarm has been triggered - {{now().strftime("%H:%M on %w %b" )}}'
        data:
          actions:
            - action: notify_action_disarm_alarm
              title: "Disarm now"
              tag: "house-alarm-notification"

- id: notify_action_disarm_alarm
  alias: Notification action - Disarm alarm
  trigger:
    platform: event
    event_type: html5_notification.clicked
    event_data:
     action: notify_action_disarm_alarm
  action:
    service: alarm_control_panel.alarm_disarm
    data:
      entity_id: alarm_control_panel.house_alarm
      code: !secret alarm_code