- alias: Bedroom Sleep Timer Triggered
  id: 'bedroom_sleep_timer_triggered'
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.bedroom_sleep_timer
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.bedroom_tv
