- alias: Bedroom Toggle Lights
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0001f354ea
      click_type: single
  action:
    service: light.toggle
    data:
      entity_id: group.bedroom_lights

- alias: Bedroom Double Click Next Scene
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0001f354ea
      click_type: double
  action:
    - service: input_select.select_next
      entity_id: input_select.input_bedroom_scenes

- alias: Bedroom Hold Goodnight
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0001f354ea
      click_type: long_click_press
  action:
    service: script.good_night