- alias: Bedroom Dimmer Off
  trigger:
    platform: state
    entity_id: sensor.bedroom_dimmer_action
    to: 'off-press'
  action:
    - service: light.turn_off
      data:
        entity_id:
          - light.bedroom_reading_lights
          - light.bedroom_ceiling

- alias: Bedroom Dimmer On
  trigger:
    platform: state
    entity_id: sensor.bedroom_dimmer_action
    to: 'on-press'
  action:
    - service: light.turn_on
      data:
        brightness_pct: 100
        entity_id:
          - light.bedroom_reading_lights
          - light.bedroom_ceiling

# - alias: Bedroom Dimmer Up
#   trigger:
#     platform: state
#     entity_id: sensor.bedroom_dimmer_action
#     to: 'up-press'
#   action:


# - alias: Bedroom Dimmer Down
#   trigger:
#     platform: state
#     entity_id: sensor.bedroom_dimmer_action
#     to: 'down-press'
#   action: