# Lounge button
- alias: Lounge Button Single
  trigger:
    platform: state
    entity_id: sensor.lounge_button_click
    to: 'single'
  action:
    - service: light.toggle
      data:
        entity_id: light.lounge_lights
        brightness_pct: 100
    - service: light.toggle
      data:
        entity_id: light.gateway_light_7811dcb25e74
        brightness_pct: 100

- alias: Lounge Button Double
  trigger:
    platform: state
    entity_id: sensor.lounge_button_click
    to: 'double'
  action:
    service: scene.turn_on
    data:
      entity_id: scene.lounge_chill

- alias: Lounge Button Hold
  trigger:
    platform: state
    entity_id: sensor.lounge_button_click
    to: 'long'
  action:
    service: script.good_night
# LOUNGE BUTTON END

# KITCHEN BUTTON
- alias: Kitchen Button Single
  trigger:
    platform: state
    entity_id: sensor.kitchen_button_click
    to: 'single'
  action:
    service: light.toggle
    data:
      entity_id: light.kitchen_lights
      brightness_pct: 100

- alias: Kitchen Button Double
  trigger:
    platform: state
    entity_id: sensor.kitchen_button_click
    to: 'double'
  action:
    service: light.toggle
    data:
      entity_id:
        - light.conservatory_lights
      brightness_pct: 100

- alias: Kitchen Button Hold Not Playing
  trigger:
    platform: state
    entity_id: sensor.kitchen_button_click
    to: 'long'
  condition:
    condition: template
    value_template: '{{ states("media_player.downstairs") != "playing" }}'
  action:
    service: script.play_radio_in_kitchen

- alias: Kitchen Button Hold When Playing
  trigger:
    platform: state
    entity_id: sensor.kitchen_button_click
    to: 'long'
  condition:
    condition: template
    value_template: '{{ states("media_player.downstairs") == "playing" }}'
  action:
    service: media_player.turn_off
    data:
      entity_id: media_player.downstairs

# KITCHEN BUTTON END

# STEVE BUTTON
- alias: Bedroom Toggle Lights
  trigger:
    platform: state
    entity_id: sensor.bedroom_button_click
    to: 'single'
  action:
    service: light.toggle
    data:
      entity_id: group.bedroom_lights

- alias: Bedroom Double Click Next Scene
  trigger:
    platform: state
    entity_id: sensor.bedroom_button_click
    to: 'double'
  action:
    - service: input_select.select_next
      entity_id: input_select.input_bedroom_scenes

- alias: Bedroom Hold Goodnight
  trigger:
    platform: state
    entity_id: sensor.bedroom_button_click
    to: 'long'
  action:
    service: script.good_night
# STEVE BUTTON END


- alias: Ikea button 1 On
  trigger:
    platform: state 
    entity_id: sensor.ikea_switch_1_click
    to: 'on'
  action:
    service: switch.turn_on
    entity_id: switch.bf5bde9e7cf9134ab6kmf7

- alias: Ikea button 1 Off
  trigger:
    platform: state 
    entity_id: sensor.ikea_switch_1_click
    to: 'off'
  action:
    service: switch.turn_off
    entity_id: switch.bf5bde9e7cf9134ab6kmf7