# SOPHIE BUTTON
- alias: Sophie Button Single
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d00035a259e
      click_type: single
  action:
    service: scene.turn_on
    data:
      entity_id: scene.bedroom_all_lights

- alias: Sophie Button Double
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d00035a259e
      click_type: double
  action:
    service: script.good_night

- alias: Sophie Button Hold
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d00035a259e
      click_type: long_click_press
  action:
    service: scene.turn_on
    data:
      entity_id: scene.bedroom_sophie_reading
# SOPHIE BUTTON END

# KITCHEN BUTTON
- alias: Kitchen Button Single
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0002fbe926
      click_type: single
  action:
    service: light.toggle
    data:
      entity_id: light.kitchen_lights
      brightness_pct: 100

- alias: Kitchen Button Double
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0002fbe926
      click_type: double
  action:
    service: script.good_night

- alias: Kitchen Button Hold Not Playing
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0002fbe926
      click_type: long_click_press
  condition:
    condition: template
    value_template: '{{ states("media_player.downstairs") != "playing" }}'
  action:
    service: script.play_radio_in_kitchen

- alias: Kitchen Button Hold When Playing
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0002fbe926
      click_type: long_click_press
  condition:
    condition: template
    value_template: '{{ states("media_player.downstairs") == "playing" }}'
  action:
    service: media_player.turn_off
    data:
      entity_id: media_player.downstairs

# KITCHEN BUTTON END

# STEVE BUTTON
- alias: Bedroom Toggle Lights
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0001f354ea
      click_type: single
  action:
    service: light.toggle
    data:
      entity_id: group.bedroom_lights

- alias: Bedroom Double Click Next Scene
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0001f354ea
      click_type: double
  action:
    - service: input_select.select_next
      entity_id: input_select.input_bedroom_scenes

- alias: Bedroom Hold Goodnight
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0001f354ea
      click_type: long_click_press
  action:
    service: script.good_night
# STEVE BUTTON END