# SOPHIE BUTTON
- alias: Sophie Button Single
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d00035a259e
      click_type: single
  action:
    service: scene.turn_on
    data:
      entity_id: scene.bedroom_all_lights

- alias: Sophie Button Double
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d00035a259e
      click_type: double
  action:
    service: script.good_night

- alias: Sophie Button Hold
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d00035a259e
      click_type: long_click_press
  action:
    service: scene.turn_on
    data:
      entity_id: scene.bedroom_sophie_reading
# SOPHIE BUTTON END

# KITCHEN BUTTON
- alias: Kitchen Button Single
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0002fbe926
      click_type: single
  action:
    service: light.toggle
    data:
      entity_id: light.kitchen_lights
      brightness_pct: 100

- alias: Kitchen Button Double
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0002fbe926
      click_type: double
  action:
    service: script.good_night

- alias: Kitchen Button Hold
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0002fbe926
      click_type: long_click_press
  action:
    service: script.play_radio_in_kitchen
# KITCHEN BUTTON END
