## When motion is detected, trigger an image scan
#- alias: Doods scanning
#  trigger:
#    - platform: state
#      entity_id:
#        - binary_sensor.ffmpeg_motion
#  action:
#    - service: image_processing.scan
#      entity_id: image_processing.doods_g3_flex_low_res
#
# When something is detected on the camera, send an alert
- alias: Detected Camera
  trigger:
    platform: mqtt
    topic: frigate/events
  conditions:
    condition: template
    value_template: "{{ trigger.payload_json['type'] == 'new' }}"
  action:
    - service: telegram_bot.send_photo
      data_template:
        message_tag: "{{ trigger.payload_json['after']['camera'] }}"
        url: http://192.168.1.61:5001/api/events/{{trigger.payload_json["after"]["id"]}}/thumbnail.jpg
        caption: >-
          A {{trigger.payload_json["after"]["label"]}} was detected on {{ trigger.payload_json['after']['camera'] }}.


