# When motion is detected, trigger an image scan
- alias: Doods scanning
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.ffmpeg_motion
  action:
    - service: image_processing.scan
      entity_id: image_processing.doods_g3_flex

# When something is detected on the camera, send an alert
- alias: Detected Camera
  trigger:
    platform: template
    value_template: "{% if states.image_processing.doods_g3_flex_low_res %}{{ states.image_processing.doods_g3_flex_low_res.attributes.matches|length }}{% else %}0{% endif %}"
  action:
    - service: telegram_bot.send_photo
      data_template:
        file: /config/www/g3_flex_latest.jpg
        caption: >-
          {% if states.image_processing.doods_g3_flex_low_res.attributes.matches|length > 0 %}
            {%- for entity in states.image_processing.doods_g3_flex_low_res.attributes.matches %}
              {%- for match in states.image_processing.doods_g3_flex_low_res.attributes.matches[entity] %}
                {{ entity }} ({{ match.score | round }}%)
              {% endfor -%}
            {% endfor -%}
          {% else %}
            Nothing detected
          {% endif %}

