- alias: "Car Mileage"
  trigger:
    platform: state
    entity_id: sensor.330i_mileage
  action:
    - service: ifttt.trigger
      data_template:
        event: 330i_mileage
        value1: "{{{ states.sensor['330i_mileage'].last_changed }}"
        value2: "{{ states('sensor.330i_mileage') }}"