- alias: "Car Mileage"
  trigger:
    platform: state
    entity_id: sensor.330i_mileage
  action:
    - service: ifttt.trigger
      data:
        event: 330i_mileage
        value1: {{ as_timestamp(now()) }}
        value2: {{ states('sensor.330i_mileage') }}