- alias: "Doorbell Notifications"
  trigger:
      platform: state
      entity_id: binary_sensor.doorbell_button_2
      to: 'on'
  action:
      - service: telegram_bot.send_message
        data:
            message: "Door bell pressed at {{ as_timestamp(now()) | timestamp_custom(\"%H:%M\") }}"