- alias: "Doorbell Notifications"
  trigger:
    platform: state
    entity_id: binary_sensor.doorbell_button_2
    to: 'on'
  condition:
    condition: template
    value_template: "{{ (as_timestamp(now()) - as_timestamp(state_attr('automation.doorbell_notifications', 'last_triggered') | default(0)) | int > 5)}}"
  action:
    - service: telegram_bot.send_message
      data:
        message: "Door bell pressed at {{ as_timestamp(now()) | timestamp_custom(\"%H:%M\") }}"
    - service: camera.snapshot
      data:
        entity_id: camera.g3_flex
        filename: /config/www/camera-snapshot.jpg
    - delay:
        seconds: 2
    - service: telegram_bot.send_photo
      data: 
        file: /config/www/camera-snapshot.jpg
        caption: Doorbell

- alias: "Doorbell Camera"
  trigger:
    platform: state
    entity_id: binary_sensor.doorbell_button_2
    to: 'on'
  condition:
    condition: template
    value_template: "{{ (as_timestamp(now()) - as_timestamp(state_attr('automation.doorbell_camera', 'last_triggered') | default(0)) | int > 5)}}"
  action:
    - service: camera.play_stream
      data:
        entity_id: camera.g3_flex
        media_player: media_player.kitchen_display

- alias: "Doorbell Office Notification"
  trigger:
    platform: state
    entity_id: binary_sensor.doorbell_button_2
    to: 'on'
  condition:
    condition: template
    value_template: "{{ (as_timestamp(now()) - as_timestamp(state_attr('automation.doorbell_office_notification', 'last_triggered') | default(0)) | int > 5)}}"
  action:
    - service: media_player.play_media
      data:
        entity_id: media_player.home_office_speaker
        media_content_id: !secret doorbell_mp3
        media_content_type: music
