- alias: "Doorbell Notifications"
  trigger:
    platform: state
    entity_id: binary_sensor.doorbell_button_2
    to: 'on'
  action:
    - service: telegram_bot.send_message
      data:
        message: "Door bell pressed at {{ as_timestamp(now()) | timestamp_custom(\"%H:%M\") }}"
    - service: camera.snapshot
      data:
        entity_id: camera.g3_flex
        filename: /config/www/camera-snapshot.jpg
    - delay:
        seconds: 2
    - service: telegram_bot.send_photo
      data: 
        file: /config/www/camera-snapshot.jpg
        caption: Doorbell