- alias: 'Front door opened on Halloween'
  trigger:
    - platform: state
      entity_id: binary_sensor.front_door_contact
      to: 'on'
  action:
    - service: media_player.volume_set
      data:
        entity_id: media_player.downstairs
        volume_level: 0.7
    - service: media_player.play_media
      data:
        entity_id: media_player.downstairs
        media_content_id: !secret halloween_sound_url
        media_content_type: music
    - service: yeelight.set_mode
      data:
        entity_id: light.yeelight_bslamp1_7c49eb28d971
        mode: rgb
    - service: light.turn_on
      data:
        entity_id: group.all_lights
        brightness_pct: 100
    - service: light.turn_on
      data:
        entity_id: group.all_lights
        flash: short
    - service: light.turn_on
      data:
        entity_id: group.all_lights
        flash: long
    - service: light.turn_on
      data:
        entity_id: group.hallway
        brightness_pct: 100
    - service: light.turn_on
      data:
        entity_id: group.lounge_lights
        brightness_pct: 100
  condition:
    condition: template
    value_template: "{{ as_timestamp(now()) | timestamp_custom(\"%d/%m\", True) == '31/10' }}"

- id: front_door_opened_alert
  alias: 'Front door opened alert'
  trigger:
    - platform: state
      entity_id: binary_sensor.front_door_contact
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: "{{ (as_timestamp(now()) - as_timestamp(state_attr('automation.front_door_opened_alert', 'last_triggered') | default(0)) | int > 5)}}"
  action:
    - service: telegram_bot.send_message
      data:
        message: "Front door opened at {{ as_timestamp(now()) | timestamp_custom(\"%H:%M\") }}"
    - service: camera.record
      data:
        entity_id: camera.g3_flex_low_res
        filename: /config/www/camera-latest.mp4
        lookback: 8
        duration: 5
    - delay:
        seconds: 15
    - service: telegram_bot.send_video
      data:
        file: /config/www/camera-latest.mp4
        caption: Front door

- id: front_door_opened_show_display
  alias: 'Front door opened show display'
  trigger:
    - platform: state
      entity_id: binary_sensor.front_door_contact
      to: 'on'
  condition:
    - condition: template
      value_template: '{{ states("media_player.downstairs") != "playing" }}'
  action:
    - service: camera.play_stream
      data:
        entity_id: camera.g3_flex
        media_player: media_player.kitchen_display

- id: office_door_opened_alert
  alias: 'Office door opened alert'
  trigger:
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d0003589af9
      to: 'on'
  action:
    - service: telegram_bot.send_message
      data:
        message: "Office door opened at {{ as_timestamp(now()) | timestamp_custom(\"%H:%M\") }}"
    - service: notify.google_assistant_broadcast
      data:
        message: "Office door opened at {{ as_timestamp(now()) | timestamp_custom(\"%H:%M\") }}"
    - service: camera.record
      data:
        entity_id: camera.g3_flex_low_res
        filename: /config/www/camera-latest.mp4
        lookback: 5
        duration: 5
    - delay:
        seconds: 15
    - service: telegram_bot.send_video
      data:
        file: /config/www/camera-latest.mp4
        caption: Office door opened

- id: kitchen_door_opened_alert
  alias: 'Kitchen doors opened alert'
  trigger:
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d00035c0c9a
      to: 'on'
  action:
    - service: notify.home_alerts
      data:
        message: "Bi-fold door opened at {{ as_timestamp(now()) | timestamp_custom(\"%H:%M\") }}"

- id: back_door_opened_alert
  alias: 'Back door opened alert'
  trigger:
    - platform: state
      entity_id: binary_sensor.back_door_contact
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: "{{ (as_timestamp(now()) - as_timestamp(state_attr('automation.back_door_opened_alert', 'last_triggered') | default(0)) | int > 5)}}"
  action:
    - service: telegram_bot.send_message
      data:
        message: "Back door opened at {{ as_timestamp(now()) | timestamp_custom(\"%H:%M\") }}"
    - service: camera.record
      data:
        entity_id: camera.garden
        filename: /config/www/camera-garden-latest.mp4
        lookback: 8
        duration: 5
    - delay:
        seconds: 15
    - service: telegram_bot.send_video
      data:
        file: /config/www/camera-garden-latest.mp4
        caption: Garden