- alias: "Doorbell Notifications"
  trigger:
    platform: state
    entity_id: binary_sensor.doorbell_button
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: "{{ (as_timestamp(now()) - as_timestamp(state_attr('automation.doorbell_notifications', 'last_triggered') | default(0)) | int > 5)}}"
  action:
    - service: light.turn_on
      data:
        entity_id: light.twigs_light
        brightness_pct: 100
        flash: short
    - service: telegram_bot.send_message
      data:
        message: "Door bell pressed at {{ as_timestamp(now()) | timestamp_custom(\"%H:%M\") }}"
    - service: camera.snapshot
      data:
        entity_id: camera.front_2
        filename: /config/www/camera-snapshot.jpg
    - delay:
        seconds: 2
    - service: telegram_bot.send_photo
      data:
        file: /config/www/camera-snapshot.jpg
        caption: Doorbell

- alias: "Doorbell Camera"
  trigger:
    platform: state
    entity_id: binary_sensor.doorbell_button
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: "{{ (as_timestamp(now()) - as_timestamp(state_attr('automation.doorbell_camera', 'last_triggered') | default(0)) | int > 5)}}"
      - condition: template
        value_template: '{{ states("media_player.downstairs") != "playing" }}'
  action:
    - service: camera.play_stream
      data:
        entity_id: camera.front_2
        media_player: media_player.kitchen_display

- alias: "Doorbell Music Alert"
  trigger:
    platform: state
    entity_id: binary_sensor.doorbell_button
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: "{{ (as_timestamp(now()) - as_timestamp(state_attr('automation.doorbell_music_alert', 'last_triggered') | default(0)) | int > 5)}}"
      - condition: template
        value_template: "{{ (now().strftime('%Y-%m-%d')) != '2020-02-08' }}"
      - condition: or
        conditions:
        - condition: template
          value_template: '{{ states("media_player.downstairs") == "playing" }}'
        - condition: state
          entity_id: 'switch.doorbell_chime_active'
          state: 'off'
  action:
    - service: notify.google_assistant_broadcast
      data_template:
        message: "There is someone at the door"

- alias: "Doorbell Office Notification"
  trigger:
    platform: state
    entity_id: binary_sensor.doorbell_button
    to: 'on'
  condition:
    condition: template
    value_template: "{{ (as_timestamp(now()) - as_timestamp(state_attr('automation.doorbell_office_notification', 'last_triggered') | default(0)) | int > 5)}}"
  action:
    - service: scene.create
      data:
        scene_id: homeoffice_snapshot
        snapshot_entities:
          - media_player.home_office_speaker
    - service: media_player.play_media
      data:
        entity_id: media_player.home_office_speaker
        media_content_id: !secret doorbell_mp3
        media_content_type: music
    - service: scene.turn_on
      data:
        entity_id: scene.homeoffice_snapshot
