- alias: Ensuite motion on
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d000223ce57
      from: 'off'
      to: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: light.shelly_e

- alias: Ensuite motion off
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d000223ce57
    from: 'on'
    to: 'off'
    for:
      minutes: 3
  action:
    - service: light.turn_off
      data:
        entity_id: light.shelly_e