- alias: Ensuite motion on
  trigger:
    - platform: state
      entity_id: binary_sensor.ensuite_motion_occupancy
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: time
        before: '19:00:00'
  action:
    - service: light.turn_on
      data:
        entity_id: light.shelly_e

- alias: Ensuite motion off
  trigger:
    platform: state
    entity_id: binary_sensor.ensuite_motion_occupancy
    to: 'off'
    for:
      minutes: 3
  action:
    - service: light.turn_off
      data:
        entity_id: light.shelly_e