- alias: Family bathroom motion on
  trigger:
    platform: state
    entity_id: binary_sensor.bathroom_motion_occupancy
    to: 'on'
  condition:
    - condition: state # after 20 mins before sunset
      entity_id: binary_sensor.activate_motion_lights
      state: "on"
  action:
    - choose:
      - conditions:
          condition: or
          conditions:
          - condition: time
            after: "18:00:00"
            before: "08:00:00"
        sequence:
          - service: light.turn_on
            data:
              entity_id: light.bathroom_light_light
              brightness_pct: 100
      default:
        - service: light.turn_on
          data:
            entity_id: light.shelly_f
            brightness_pct: 100

- alias: Family bathroom motion off
  trigger:
    platform: state
    entity_id: binary_sensor.bathroom_motion_occupancy
    to: 'off'
    for:
      minutes: 2
  action:
    - service: light.turn_off
      data:
        entity_id: light.shelly_f
    - service: light.turn_off
      data:
        entity_id: light.bathroom_light_light