- alias: 'Front door opened'
  trigger:
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d0002253f18 # front door
      to: 'on'
  action:
    - service: counter.increment
      data:
        entity_id: counter.door_opened
    - service: light.turn_on
      data:
        entity_id: group.all_lights
    - service: light.turn_on
      data:
        entity_id: group.all_lights
        flash: short
    - delay:
        seconds: 5
    - service: light.turn_on
      data:
        entity_id: group.all_lights
        flash: short
    - delay:
        seconds: 5
    - service: light.turn_off
      data:
        entity_id: group.all_lights
        transition: 5
    - delay:
        seconds: 5
    - service: light.turn_on
      data:
        entity_id: group.hallway
        brightness_pct: 100
    - service: media_player.volume_set
      data:
        entity_id: media_player.downstairs
        volume_level: 0.5
    - service: media_player.play_media
      data:
        entity_id: media_player.downstairs
        media_content_id: !secret halloween_sound_url
        media_content_type: music