- alias: 'Garden Lights on'
  trigger:
  - event: sunset
    platform: sun
    offset: "-00:35:00"
  action:
  - service: light.turn_on
    data:
      transition: 900 # 15 minutes
      brightness_pct: 100
      entity_id: light.garden_lights
  alias: Lights on at sunset
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: 'person.steve_edson'
        state: 'home'
      - condition: state
        entity_id: 'person.sophie'
        state: 'home'

- alias: 'Garden Lights off'
  trigger:
    platform: time
    at: '23:00:00'
  action:
  - service: light.turn_off
    data:
      transition: 15 # 15 seconds
      entity_id: light.garden_lights