- alias: xiaoma switch click
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0001f354ea
      click_type: single
  action:
    service: light.toggle
    data:
      entity_id: group.bedroom_lights

- alias: xiaoma switch double click
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0001f354ea
      click_type: double
  action:
    service: script.good_night