- alias: Kitchen Dimmer On
  trigger:
    platform: state
    entity_id: sensor.0x0017880106349624_action
    to: 'on-press'
  action:
    - service: light.turn_on
      data:
        entity_id: light.conservatory_lights
        brightness_pct: 100

- alias: Kitchen Dimmer Off
  trigger:
    platform: state
    entity_id: sensor.0x0017880106349624_action
    to: 'off-press'
  action:
    - service: light.turn_off
      data:
        entity_id: light.conservatory_lights