- alias: Lights off at night
  action:
  - data:
      entity_id: group.all_lights
    service: light.turn_off
  # - data:
  #     entity_id: switch.my_smart_plug
  #   service: switch.turn_off
  condition: []
  id: '1509874606449'
  trigger:
    platform: time
    at: '00:30:00'
