- alias: Lights off at night
  id: '1509874606449'
  trigger:
    platform: time
    at: '00:30:00'
  action:
  - service: light.turn_off
    data:
      entity_id: group.all_lights
  - service: switch.turn_off
    data:
      entity_id: switch.bf0b57d12c6b4b8272vkpj
  - service: switch.turn_off
    data:
      entity_id: switch.32002710bcddc226b4b0
  - service: switch.turn_off
    data:
      entity_id: switch.bf4cadf5e3e38fddf078v2