- alias: Nursery Light On
  description: ""
  trigger:
    - platform: device
      domain: mqtt
      device_id: 3464be2783be93efb76bb633855b9bff
      type: action
      subtype: "on"
      discovery_id: 0x84fd27fffe2cec76 action_on
  condition: [ ]
  action:
    - service: light.turn_on
      target:
        entity_id: light.yeelight_bslamp1_7c49eb28d971
  mode: single

- alias: Nursery Light Off
  description: ""
  trigger:
    - platform: device
      domain: mqtt
      device_id: 3464be2783be93efb76bb633855b9bff
      type: action
      subtype: "off"
      discovery_id: 0x84fd27fffe2cec76 action_off
  condition: [ ]
  action:
    - service: light.turn_off
      target:
        entity_id: light.yeelight_bslamp1_7c49eb28d971
  mode: single

