- alias: Lounge Scenes
  trigger:
    platform: state
    entity_id: input_select.input_scenes
  action:
    service: scene.turn_on
    data_template:
      entity_id: scene.{{trigger.to_state.state}}