- alias: Kitchen motion
  trigger:
    platform: time
    at: '21:30:00'
  action:
    - service: light.turn_off
      data:
        entity_id: light.shelly_b

- alias: Kitchen motion before 2130
  trigger:
    - platform: state
      entity_id: binary_sensor.kitchen_motion_occupancy
      from: 'off'
      to: 'on'
  condition:
    condition : and
    conditions:
        - condition: time
          before: '21:30:00'
        - condition: or
          conditions:
          - condition: state # after 20 mins before sunset
            entity_id: binary_sensor.night
            state: "on"
          - condition: state
            entity_id: input_boolean.guest_mode
            state: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: light.shelly_b
    - service: light.turn_on
      data:
        entity_id: light.shelly_c
    - service: scene.turn_on
      data:
        entity_id: scene.table_pink_and_blue

- alias: Kitchen motion after 2130
  trigger:
    - platform: state
      entity_id: binary_sensor.kitchen_motion_occupancy
      from: 'off'
      to: 'on'
  condition:
    condition : and
    conditions:
        - condition: time
          after: '21:30:00'
        - condition: or
          conditions:
          - condition: state # after 20 mins before sunset
            entity_id: binary_sensor.night
            state: "on"
          - condition: state
            entity_id: input_boolean.guest_mode
            state: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: light.shelly_c

# Turn off kitchen light with no motion for 3 mins
- alias: Kitchen no motion 10 mins
  trigger:
    platform: state
    entity_id: binary_sensor.kitchen_motion_occupancy
    from: 'on'
    to: 'off'
    for:
      minutes: 10
  action:
    - service: light.turn_off
      data:
        entity_id: light.shelly_b
    - service: light.turn_off
      data:
        entity_id: light.shelly_c

- alias: Kitchen no motion 45 mins
  trigger:
    platform: state
    entity_id: binary_sensor.kitchen_motion_occupancy
    from: 'on'
    to: 'off'
    for:
      minutes: 45
  action:
    - service: light.turn_off
      data:
        entity_id:
          - light.table_light_1_light
          - light.table_light_2_light
          - light.table_light_3_light

- alias: Hallway motion
  trigger:
    - platform: state
      entity_id: binary_sensor.front_door_contact
      from: 'off'
      to: 'on'
  condition:
    condition : or
    conditions:
      - condition: state # after 20 mins before sunset
        entity_id: binary_sensor.night
        state: "on"
      #- condition: numeric_state
      #    entity_id: sensor.illumination_7811dcb25e74
      #    below: 700
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'on'
  action:
    - service: light.turn_on
      data:
        brightness_pct: 100
        transition: 1
        entity_id:
          - light.shelly_a
          - light.porch_lights


- alias: Hallway motion off
  trigger:
    - platform: state
      entity_id: binary_sensor.front_door_contact
      from: 'on'
      to: 'off'
      for:
        minutes: 5
  action:
    - service: light.turn_off
      data:
        entity_id:
          - light.shelly_a
          - light.porch_lights
