- alias: Netflix Mode
  trigger:
    - platform: template
      value_template: {{ is_state_attr('media_player.lounge_tv', 'app_name', 'Netflix') }}
  action:
    - service: scene.turn_on
      data:
        entity_id: scene.ocean
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sun.sun
        state: "below_horizon"