- alias: Nursery motion on - main
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0001d55c60
      from: 'off'
      to: 'on'
  condition:
    - condition: time
      before: '19:30:00'
    - condition: state # after 20 mins before sunset
      entity: binary_sensor.night
      state: "on"
  action:
    - service: light.turn_on
      data:
        entity_id: light.nursery

- alias: Nursery motion on - side
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0001d55c60
      from: 'off'
      to: 'on'
  condition:
    - condition: time
      after: '19:30:00'
    - condition: state # after 20 mins before sunset
      entity: binary_sensor.night
      state: "on"
  action:
    - service: light.turn_on
      data:
        entity_id: light.yeelight_bslamp1_7c49eb28d971
        brightness_pct: 100

- alias: Nursery motion off
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0001d55c60
    from: 'on'
    to: 'off'
    for:
      minutes: 30
  action:
    - service: light.turn_off
      data:
        entity_id: light.nursery
    - service: light.turn_off
      data:
        entity_id: light.yeelight_bslamp1_7c49eb28d971