- alias: Nursery motion on - main
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0001d55c60
      from: 'off'
      to: 'on'
  condition:
    conditions:
      - condition: time
        before: '19:30:00'
      - condition: sun # after 20 mins before sunset
        after: sunset
        after_offset: "-1:00:00"
      - condition: sun # before 1 hour after sunrise
        before: sunrise
        before_offset: "1:00:00"
  action:
    - service: light.turn_on
      data:
        entity_id: light.nursery

- alias: Nursery motion on - side
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0001d55c60
      from: 'off'
      to: 'on'
  condition:
    conditions:
      - condition: time
        after: '19:30:00'
      - condition: sun # after 20 mins before sunset
        after: sunset
        after_offset: "-1:00:00"
      - condition: sun # before 1 hour after sunrise
        before: sunrise
        before_offset: "1:00:00"
  action:
    - service: light.turn_on
      data:
        entity_id: light.yeelight_bslamp1_7c49eb28d971
        brightness_pct: 100

- alias: Nursery motion off
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0001d55c60
    from: 'on'
    to: 'off'
    for:
      minutes: 3
  action:
    - service: light.turn_off
      data:
        entity_id: light.nursery
    - service: light.turn_off
      data:
        entity_id: light.yeelight_bslamp1_7c49eb28d971