- alias: Outside Lights On At Sunset
  trigger:
    - event: sunset
      platform: sun
      offset: "-00:35:00"
  condition:
    - condition: template
      value_template: >
        {% set n = now() %}
        {{ (n.month == 12 and 1 <= n.day <= 31) or (n.month == 1 and 1 <= n.day < 6) }}
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.bf5bde9e7cf9134ab6kmf7

- alias: Outside Lights Off At Midnight
  trigger:
    platform: time
    at: '00:30:00'
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.bf5bde9e7cf9134ab6kmf7