- alias: Price Changes
  trigger:
    platform: numeric_state
    entity_id: sensor.price_trackers
    # Optional
    value_template: '{{ state.attributes.currys }}'
    # At least one of the following required
    below: 379
  action:
    service: notify.home_alerts
    data:
      title: "Price Changes"
      message: "Price has changed to £{{ states.sensor.price_trackers.attributes.currys }}"