- alias: 'Proximity'
  trigger:
    platform: template
    value_template: "{{ is_state_attr('proximity.sophie_home', 'dir_of_travel', 'towards') }}"
  action:
    - service: notify.mobile_app_steve_s_phone
      data_template:
        title: "Coming home"
        message: "On their way"
        data:
          sticky: 'true'