- alias: 'Proximity'
  trigger:
    platform: state
    entity_id: proximity.sophie_home
    # Optional
    value_template: "{{ state.attributes.dir_of_travel }}"
    to: "towards"
  action:
    - service: notify.mobile_app_steve_s_phone
      data_template:
        title: "{{ state.attributes.friendly_name }} coming home"
        message: "On their way"
        data:
          sticky: 'true'