- alias: Reset motion at midnight
  id: f520c5bf-47e0-4983-ae87-642854c79dad
  trigger:
    platform: time
    at: '00:00:00'
  action:
  - service: automation.turn_on
    entity_id:
      - automation.kitchen_motion_after_2130
      - automation.kitchen_motion_before_2130
  - service: switch.turn_on
    entity_id: switch.doorbell_chime_active