- alias: Shower motion
  trigger:
    - platform: state
      entity_id: binary_sensor.landing_sensor_motion
      from: 'off'
      to: 'on'
  condition:
    condition: or
    conditions:
      - condition: sun # after 20 mins before sunset
        after: sunset
        after_offset: "-1:00:00"
      - condition: sun # before 1 hour after sunrise
        before: sunrise
        before_offset: "1:00:00"
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: light.shelly_e

- alias: Shower no motion
  trigger:
    platform: state
    entity_id: binary_sensor.landing_sensor_motion
    from: 'on'
    to: 'off'
    for:
      minutes: 10
  action:
    - service: light.turn_off
      data:
        entity_id: light.shelly_e