- alias: 'Home Assistant Started'
  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: notify.home_assistant
      data:
        message: 'Home assistant has started'
#    - service: notify.google_assistant_broadcast
#      data:
#        message: "Home assistant is back online"
#