- alias: 'Home Assistant Started'
  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: notify.telegram
      data:
        message: 'Home assistant has started'
    - event: tileboard
      event_data:
        command: refresh
#    - service: notify.google_assistant_broadcast
#      data:
#        message: "Home assistant is back online"
#