- alias: Stock Status Change
  trigger:
    platform: state
    entity_id: sensor.pn61_status
  action:
    - service: telegram_bot.send_message
      data_template:
        message: "PN61 Stock Status {{ trigger.to_state.state }}"