- alias: Lights Sync (On)
  action:
  - alias: turn switch on
    data:
      entity_id: switch.tplink_switch
    service: switch.turn_on
  condition: []
  id: '1508056350422'
  trigger:
  - entity_id: light.twigs
    from: 'off'
    platform: state
    to: 'on'
