- alias: Lights Sync (Off)
  action:
  - alias: turn switch off
    data:
      entity_id: switch.tplink_switch
    service: switch.turn_off
  condition: []
  trigger:
  - entity_id: light.twigs
    from: 'on'
    platform: state
    to: 'off'
