- alias: 'Telegram Heating On'
  hide_entity: true
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      data: '/heating_on'
  action:
    - service: script.boost_heating