- alias: BBC One
  trigger:
  - platform: state
    entity_id: input_select.channel
    to: BBC One
  action:
    service: mqtt.publish
    data:
      topic: sky_command
      payload: "1 1 5"

- alias: BBC Two
  trigger:
  - platform: state
    entity_id: input_select.channel
    to: BBC Two
  action:
    service: mqtt.publish
    data:
      topic: sky_command
      payload: "1 0 2"

- alias: ITV
  trigger:
  - platform: state
    entity_id: input_select.channel
    to: ITV
  action:
    service: mqtt.publish
    data:
      topic: sky_command
      payload: "1 0 3"

- alias: Channel 4
  trigger:
  - platform: state
    entity_id: input_select.channel
    to: Channel 4
  action:
    service: mqtt.publish
    data:
      topic: sky_command
      payload: "1 3 8"

- alias: Sky 1
  trigger:
  - platform: state
    entity_id: input_select.channel
    to: Sky 1
  action:
    service: mqtt.publish
    data:
      topic: sky_command
      payload: "1 0 6"