- alias: Upcoming feed alert
  trigger:
    - platform: numeric_state
      entity_id: sensor.seconds_since_bottle_warmed
      above: 9000
  condition:
    - condition: time
      after: '09:00:00'
      before: '23:00:00'
  action:
    - service: telegram_bot.send_message
      data_template:
        message: "Last feed was {{ states('sensor.last_feed_readable') }}, get ready for next feed"