- alias: Kitchen Vacuum Alert
  action:
    - service: notify.home_alerts
      data_template:
        message: "The vacuum will start tonight at 11pm, please tidy the kitchen area"
  condition:
    condition: and
    conditions:
      - condition: time
        weekday:
          - wed
  trigger:
    platform: time
    at: '19:30:00'

- alias: Kitchen Vacuum
  action:
    - service: notify.home_alerts
      data:
        entity_id: vacuum.xiaomi_vacuum_cleaner
        zones: [[23199,24008,29749,28808], [29654,26405,31454,28355]]
        repeats: 3
  condition:
    condition: and
    conditions:
      - condition: time
        weekday:
          - wed
  trigger:
    platform: time
    at: '23:00:00'

- alias: Lounge Vacuum Alert
  action:
    - service: notify.home_alerts
      data_template:
        message: "The vacuum will start tonight at 11pm, please tidy the lounge area"
  condition:
    condition: and
    conditions:
      - condition: time
        weekday:
          - thu
  trigger:
    platform: time
    at: '19:30:00'

- alias: Lounge Vacuum
  action:
    - service: notify.home_alerts
      data:
        entity_id: vacuum.xiaomi_vacuum_cleaner
        zones: [[25083,19323,31833,23373]]
        repeats: 3
  condition:
    condition: and
    conditions:
      - condition: time
        weekday:
          - thu
  trigger:
    platform: time
    at: '23:00:00'

- alias: Hallway Vacuum Alert
  action:
    - service: notify.home_alerts
      data_template:
        message: "The vacuum will start tonight at 11pm, please tidy the lounge area"
  condition:
    condition: and
    conditions:
      - condition: time
        weekday:
          - fri
  trigger:
    platform: time
    at: '19:30:00'

- alias: Hallway Vacuum
  action:
    - service: notify.home_alerts
      data:
        entity_id: vacuum.xiaomi_vacuum_cleaner
        zones: [[29684,23319,33034,25969]]
        repeats: 3
  condition:
    condition: and
    conditions:
      - condition: time
        weekday:
          - fri
  trigger:
    platform: time
    at: '23:00:00'
