- alias: kitchen motion
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0001643c27
    from: 'off'
    to: 'on'
  condition:
    condition : or
    conditions:
      - condition: sun # 20 mins before sunset
        after: sunset
        after_offset: "-0:20:00"
      - condition: sun # 1 hour after sunrise
        before: sunrise
        before_offset: "1:00:00"
  action:
    - service: light.turn_on
      data:
        entity_id: group.kitchen_lights
        brightness_pct: 100 


# Dim the lights after no motion
- alias: Kitchen no motion 5 mins
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0001643c27
    from: 'on'
    to: 'off'
    for:
      minutes: 2
  condition:
    condition: state
    entity_id: group.kitchen_lights
    state: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: group.kitchen_lights
        brightness_pct: 25

#Turn off kitchen light with no motion for 15 mins
- alias: Kitchen no motion 15 mins
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0001643c27
    from: 'on'
    to: 'off'
    for:
      minutes: 8
  condition:
    condition: state
    entity_id: group.kitchen_lights
    state: 'on'
  action:
    - service: light.turn_off
      data:
        entity_id: group.kitchen_lights

- alias: Cube rotation clockwise
  trigger:
    platform: event
    event_type: cube_action
    event_data:
      entity_id: binary_sensor.cube_158d0001041dc7
      action_type: rotate
  condition:
    condition: template
    value_template: "{{ (trigger.event.data.action_value|float) > 0 }}"
  action:
    - service: scene.turn_on
      entity_id: scene.deep_blue

- alias: Cube rotation anticlockwise
  trigger:
    platform: event
    event_type: cube_action
    event_data:
      entity_id: binary_sensor.cube_158d0001041dc7
      action_type: rotate
  condition:
    condition: template
    value_template: "{{ (trigger.event.data.action_value|float) < 0 }}"
  action:
    - service: scene.turn_on
      entity_id: scene.bright

- alias: Cube volume
  trigger:
    platform: event
    event_type: cube_action
    event_data:
      entity_id: binary_sensor.cube_158d0001041dc7
      action_type: shake_air
  action:
    - service: light.toggle
      entity_id: group.lounge_lights