- alias: kitchen motion
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0001643c27
    from: 'off'
    to: 'on'
  condition:
    condition : or
    conditions:
      - condition: sun # after 20 mins before sunset
        after: sunset
        after_offset: "-1:00:00"
      - condition: sun # before 1 hour after sunrise
        before: sunrise
        before_offset: "1:00:00"
      - condition: numeric_state
        state: sensor.illumination_7811dcb25e74
        below: 250  
  action:
    - service: light.turn_on
      data:
        entity_id: group.kitchen_lights
        brightness_pct: 100 
        rgb_color: 255,0,255

- alias: kitchen led motion
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0001643c27
    from: 'off'
    to: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: light.cupboard
        brightness_pct: 100

- alias: Kitchen cupboard no motion 4 mins
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0001643c27
    from: 'on'
    to: 'off'
    for:
      minutes: 4
  condition:
    condition: state # after 20 mins before sunset
    entity_id: light.kitchen_table
    state: 'off'
  action:
    - service: light.turn_off
      data:
        entity_id: light.cupboard


# Dim the lights after no motion
- alias: Kitchen no motion 5 mins
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0001643c27
    from: 'on'
    to: 'off'
    for:
      minutes: 5
  condition:
    condition: state
    entity_id: group.kitchen_lights
    state: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: group.kitchen_lights
        brightness_pct: 25

#Turn off kitchen light with no motion for 15 mins
- alias: Kitchen no motion 10 mins
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0001643c27
    from: 'on'
    to: 'off'
    for:
      minutes: 10
  condition:
    condition: state
    entity_id: group.kitchen_lights
    state: 'on'
  action:
    - service: light.turn_off
      data:
        entity_id: group.kitchen_lights

- alias: Cube volume up
  trigger:
    platform: event
    event_type: xiaomi_aqara.cube_action
    event_data:
      entity_id: binary_sensor.xiaomi_cube
      action_type: rotate
  condition:
    condition: template
    value_template: "{{ (trigger.event.data.action_value|float) > 0 }}"
  action:
    - service: script.surround_sound_vol_up

- alias: Cube volume down
  trigger:
    platform: event
    event_type: xiaomi_aqara.cube_action
    event_data:
      entity_id: binary_sensor.xiaomi_cube
      action_type: rotate
  condition:
    condition: template
    value_template: "{{ (trigger.event.data.action_value|float) < 0 }}"
  action:
    - service: script.surround_sound_vol_down

- alias: Cube flip90
  trigger:
    platform: event
    event_type: xiaomi_aqara.cube_action
    event_data:
      entity_id: binary_sensor.xiaomi_cube
      action_type: flip90
  action:
    - service: input_select.select_next
      entity_id: input_select.input_scenes

- alias: Cube flip180
  trigger:
    platform: event
    event_type: xiaomi_aqara.cube_action
    event_data:
      entity_id: binary_sensor.xiaomi_cube
      action_type: flip180
  action:
    - service: scene.turn_on
      entity_id: scene.ocean

- alias: Cube swing
  trigger:
    platform: event
    event_type: xiaomi_aqara.cube_action
    event_data:
      entity_id: binary_sensor.xiaomi_cube
      action_type: swing
  action:
    - service: script.good_night 

- alias: Cube volume
  trigger:
    platform: event
    event_type: xiaomi_aqara.cube_action
    event_data:
      entity_id: binary_sensor.xiaomi_cube
      action_type: shake_air
  action:
    - service: light.toggle
      entity_id: group.lounge_lights


- alias: Cube Tap Twice
  trigger:
    platform: event
    event_type: xiaomi_aqara.cube_action
    event_data:
      entity_id: binary_sensor.xiaomi_cube
      action_type: tap_twice 
  action:
    - service_template: >
         {% if is_state('media_player.lounge_tv', 'on') %}
          media_player.toggle
         {% elif is_state('media_player.lounge', 'on') %}
          media_player.toggle
         {% else %}
           script.pause_sky
         {% endif %}
      data_template:
        entity_id: >
         {% if is_state('media_player.lounge_tv', 'on') %}
         media_player.lounge_tv
         {% elif is_state('media_player.lounge', 'on') %}
         media_player.lounge
         {% else %}
          media_player.samsung_tv
         {% endif %}