# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - run: mv secrets.example.yaml secrets.yaml

    # Runs a single command using the runners shell
    - name: Home Assistant Configuration Check
      uses: ludeeus/action-ha-config-check@1.0.0
      with:
        # The version to use of Home Assistant ('DEV', 'RC', 'STABLE')
        version: STABLE
        # Relative path to your configuration directory if not in the root
        config_path: .
        
    # Runs a single command using the runners shell
    - name: Home Assistant Configuration Check
      uses: ludeeus/action-ha-config-check@1.0.0
      with:
        # The version to use of Home Assistant ('DEV', 'RC', 'STABLE')
        version: RC
        # Relative path to your configuration directory if not in the root
        config_path: .

    # Runs a single command using the runners shell
    - name: Home Assistant Configuration Check
      uses: ludeeus/action-ha-config-check@1.0.0
      with:
        # The version to use of Home Assistant ('DEV', 'RC', 'STABLE')
        version: DEV
        # Relative path to your configuration directory if not in the root
        config_path: .
